--
-- Table structure for table `admin`
--
DROP TABLE IF EXISTS `admin`;
CREATE TABLE IF NOT EXISTS `admin` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `image` varchar(255) DEFAULT NULL,
  `social_fb` text NOT NULL,
  `social_tw` text NOT NULL,
  `social_you` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `email`, `password`, `image`, `social_fb`, `social_tw`, `social_you`) VALUES
(1, 'admin', 'admin@site.com', '81dc9bdb52d04dc20036dbd8313ed055', 'user.png', 'https%3A%2F%2Fwww.facebook.com%2F', 'https%3A%2F%2Fwww.twitter.com%2F', 'https%3A%2F%2Fwww.youtube.com%2F');

-- --------------------------------------------------------

--
-- Table structure for table `ads`
--

DROP TABLE IF EXISTS `ads`;
CREATE TABLE IF NOT EXISTS `ads` (
  `id` int(11) NOT NULL,
  `ad_type` varchar(100) NOT NULL,
  `ad_code` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `ads`
--

INSERT INTO `ads` (`id`, `ad_type`, `ad_code`) VALUES
(1, 'banner-content', ''),
(2, 'banner-sidebar', 'PGltZyBzcmM9ImFzc2V0cy9pbWcvcGxhY2Vob2xkZXIvMzAweDI1MC5wbmciPg=='),
(3, 'banner-top', 'PGEgaHJlZj0iaHR0cHM6Ly93d3cuY29kZXN0ZXIuY29tL2l0ZW1zLzE4MDc4L3l0LXRvb2wtc3RhdGlvbi1waHAtc2NyaXB0LXdpdGgtYWRtaW4tcGFuZWw/cmVmPUxvdmVseXdlYmFwcHMiICB0YXJnZXQ9Il9ibGFuayI+PGltZyBzcmM9ImFzc2V0cy9pbWcvYWRzL3BsYWNlaG9sZGVyLWJhbm5lci5qcGciPjwvYT4='),
(4, 'popads', '');

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

DROP TABLE IF EXISTS `categories`;
CREATE TABLE IF NOT EXISTS `categories` (
  `id` int(3) NOT NULL,
  `name` text NOT NULL,
  `catSlug` varchar(255) DEFAULT NULL,
  `status` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `catSlug`, `status`) VALUES
(2, 'Youtube Videoss', '', 3),
(3, 'Music', '', 0),
(4, 'Dance', '', 0),
(6, 'Painting', '', 0),
(7, 'People', '', 3),
(8, 'Social Media', '', 0),
(9, 'Technology', '', 3),
(10, 'Youtube Video', NULL, 0);

-- --------------------------------------------------------

--
-- Table structure for table `custom_codes`
--
DROP TABLE IF EXISTS `custom_codes`;
CREATE TABLE IF NOT EXISTS `custom_codes` (
  `id` varchar(100) NOT NULL,
  `content` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `custom_codes`
--

INSERT INTO `custom_codes` (`id`, `content`) VALUES
('footer', ''),
('header', 'PCEtLWZhdmljb24tLT4NCjxsaW5rIHJlbD0ic2hvcnRjdXQgaWNvbiIgaHJlZj0iZmF2aWNvbi5pY28iIHR5cGU9ImltYWdlL3gtaWNvbiI+DQo8bGluayByZWw9Imljb24iIGhyZWY9ImZhdmljb24uaWNvIiB0eXBlPSJpbWFnZS94LWljb24iPg0KPCEtLT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PS0tPg0KDQoNCjxzdHlsZT4NCi8qPT09PT09PT09PT09PT09PT09PQ0KICAgICAgY3NzIGNvZGVzIGdvZXMgaGVyZSANCj09PT09PT09PT09PT09PT09PT0qLw0KPC9zdHlsZT4NCg0KDQo=');

-- --------------------------------------------------------

--
-- Table structure for table `pages`
--
DROP TABLE IF EXISTS `pages`;
CREATE TABLE IF NOT EXISTS `pages` (
  `id` int(100) NOT NULL,
  `name` varchar(255) NOT NULL,
  `title` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `meta_keywords` text NOT NULL,
  `meta_description` text NOT NULL,
  `other_codes` varchar(255) NOT NULL,
  `url` varchar(255) NOT NULL,
  `type` int(1) NOT NULL DEFAULT '1' COMMENT '1=>Tools, 0=>pages',
  `status` int(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pages`
--

INSERT INTO `pages` (`id`, `name`, `title`, `content`, `meta_keywords`, `meta_description`, `other_codes`, `url`, `type`, `status`) VALUES
(1, 'Tags Generator', 'YouTube Video Tag Generator Tool - YT Tool Station', 'PGgxPkFib3V0IFlUIFZpZGVvIFRhZ3MgR2VuZXJhdG9yIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4gaXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjwvZGl2Pg==', 'YouTube Keyword Tool, YouTube Tags, YouTube Tags Generator, tags for YouTube, youtube videos,   youtube video seo,    youtube videos tags,    youtube optimization,    youtube video optimization,    rank youtube videos,    rank videos on youtube,    viral videos,    how to rank youtube videos quickly,    youtuber best tool,    relevant tags,    youtube free tool,', 'Fast, Free, Easy and Best tool for youtuber\'s to find hundreds of popular video tags for youtube video optimization.', '', 'youtube-tags-generator.php', 1, 0),
(2, 'Video Downloader', 'YouTube Video Download - YT Tool Station', 'PGgxPkFib3V0IFlUIFZpZGVvIERvd25sb2FkZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', 'youtube,youtube video,video download,youtube download,free download video,youtube video free download,youtube mp3', '', '', 'youtube-videos-downloader.php', 1, 0),
(3, 'Earnings Calculator', 'YouTube Video/Channel Revenue Calculator  - YT Tool Station', 'PGgxPkFib3V0IFlUIFJldmVudWUgQ2FsY3VsYXRvciBUb29sPC9oMT4NCjxkaXY+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+IGlzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8L2Rpdj4=', 'youtube earnings,calculate the earnings,youtube revenue, calculate youtube revenue,revenue', 'Calculate the earnings from a YouTube channel using the YouTube Revenue Calculator. Estimate the YouTube earnings of your favorite YouTubers!', '', 'youtube-revenue-calculator.php', 1, 0),
(4, 'Y2MP3 converter', 'Youtube to mp3 Converter Tool - YT Tool Station', 'PGgxPkFib3V0IFlUMk1QMyBDb252ZXJ0ZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', 'Convert  mp3,youtube to mp3,video converter', 'Convert and Download MP3 from YouTube in high quality. Convert all YouTube videos to MP3 in just a few seconds. Easy to Convert and Download, fast, simply and FREE!', '', 'youtube-to-mp3-converter.php', 1, 0),
(5, 'Thumbnails Generator', 'YouTube Thumbnails Generator - YT Tool Station', 'PGgxPkFib3V0IFlUIFRodW1ibmFpbHMgR2VuZXJhdG9yIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4gaXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjwvZGl2Pg==', 'youtube,youtube thumbnails,thumbnails,youtube thumbnails creater,create youtube thumbnails,yt thumbnails,youtube tools', 'Fast, Free, Easy and Best tool for youtuber\'s to find hundreds of popular video thumbnails for youtube video optimization.', '', 'youtube-thumbnails-generator.php', 1, 0),
(6, 'Titles Generator', 'Youtube Video Titles Generator Tool - YT Tool Station', 'PGgxPkFib3V0IFlUIFZpZGVvIFRpdGxlcyBHZW5lcmF0b3IgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'youtube-titles-generator.php', 1, 0),
(7, 'Find Video Tags', 'YouTube Video Tag Finder Tool - YT Tool Station', 'PGgxPkFib3V0IFlUIFZpZGVvIFRhZ3MgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4gaXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjwvZGl2Pg==', 'youtube seo,  youtube tag generator,  how to properly tag your youtube videos,  youtube tags,  youtube tags generator,  how to tag youtube videos,  youtube,  how to tag youtube videos better, get youtube video tags, extract video tags', 'If you have a YouTube channel you are trying to get more views for, you probably want to see what tags your competition is using on their individual videos. Descriptive tags are hidden from video viewers, but here\'s how you can see what tags any YouTube video is using.', '', 'find-youtube-video-tags.php', 1, 0),
(8, 'Download Video thumbnail', 'Youtube Video Thumbnail Finder Tool - YT Tool Station', 'PGgxPkFib3V0IFlUIFZpZGVvIFRodW1ibmFpbCBGaW5kZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', 'youtube thumbnails,  video thumbnails,thumbnails', 'Thumbnail finder is a free online media application which allows you to view and download any Youtube thumbnail preview image in max resolution, HD, 1080p...', '', 'find-youtube-video-thumbnails.php', 1, 0),
(9, 'Find Channel Keywords', 'Find the Keywords of a YouTube Channel  - YT Tool Station', 'PGgxPkFib3V0IFlUIEtleXdvcmRzIEZpbmRlciBUb29sPC9oMT4NCjxkaXY+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+IGlzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8L2Rpdj4NCjxwPiZuYnNwOzwvcD4=', 'youtube keywords,channel keywords,keywords,youtube tags,find channel keywords', 'If you have a YouTube channel you are trying to get more views for, you probably want to see what keywords your competition is using on their individual channel. Descriptive keywords are hidden from video viewers, but here\'s how you can see what tags any YouTube channel is using.', '', 'find-channel-keywords.php', 1, 0),
(10, 'Trending Videos', 'Find Trending Videos in YouTube specific to a country - YT Tool Master', 'PGgxPkFib3V0IFlUIFRyZW5kaW5nIFZpZGVvcyBGaW5kZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', 'Find Trending YouTube Videos in YouTube specific to a country.', '', 'youtube-trending-videos.php', 1, 0),
(11, 'about us', 'About Us - YT Tool Station', 'PGgxPkFib3V0IFVzLSBZVCBUb29sIFN0YXRpb248L2gxPg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+Jm5ic3A7aXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg==', '', '', '', 'about-us.php', 0, 0),
(12, 'Privacy Policy', 'Privacy Policy - YT Tool Station', 'PGgxPlByaXZhY3kgUG9saWN5LSBZVCBUb29sIFN0YXRpb248L2gxPg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+Jm5ic3A7aXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg==', '', '', '', 'privacy_policy.php', 0, 0),
(13, 'find Animated thumbnails', 'Find YouTube Animated Thumbnails - YT Tool Station', 'PGgxPkhvdyBUbyBVc2UgWVQgQW5pbWF0ZWQgVGh1bWJuYWlscyBGaW5kZXI8L2gxPg0KPHA+Jm5ic3A7PC9wPg0KPGgxPjxpZnJhbWUgc3JjPSIvL3d3dy55b3V0dWJlLmNvbS9lbWJlZC9oMFdxY181aDJBRSIgd2lkdGg9IjU2MCIgaGVpZ2h0PSIzMTUiIGZyYW1lYm9yZGVyPSIwIiBhbGxvd2Z1bGxzY3JlZW49ImFsbG93ZnVsbHNjcmVlbiI+PC9pZnJhbWU+Jm5ic3A7PC9oMT4NCjxkaXY+Jm5ic3A7PC9kaXY+', '', '', '', 'find-youtube-animated-thumbnails.php', 1, 0),
(14, 'Username Checker', 'YouTube Channel Username Checker - YT Tool Station', 'PGgxPkFib3V0IENhaG5uZWwgVXNlcm5hbWUgQ2hlY2tlciBUb29sPC9oMT4NCjxkaXY+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+IGlzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8L2Rpdj4=', 'channel username,youtube channel checker,youtube channel,youtube', '', '', 'youtube-username-checker.php', 1, 0),
(15, 'Find Channel Banner', 'YouTube Channel Banner Download - YT Tool Station', 'PGgxPkFib3V0IENhaG5uZWwgQmFubmVyIERvd25sb2FkZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiBpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', 'youtube channel,youtube,youtube banner,channel art,youtube channel art', '', '', 'find-channel-banner.php', 1, 0),
(16, 'Live Subscribers Counter', 'YouTube Live Subscriber Count - YT Tool Station', 'PGgxPkFib3V0IFlUIExpdmUgU3Vic2NyaWJlciBDb3VudGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', 'live subscriber,subscribers counter,youtube,youtube subscribers', '', '', 'youtube-live-subscribers-counter.php', 1, 0),
(17, 'Live likes/dislikes counter', 'YouTube Live Likes/Dislikes Counter - YT Tool Station', 'PGgxPkFib3V0IFlUIExpa2VzL0Rpc2xpa2VzIENvdW50ZXIgVG9vbDwvaDE+DQo8ZGl2Pg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8L2Rpdj4=', 'youtube,YouTube Live,YouTube Live Likes/Dislikes Counter ,youtube likes,youtube downloader', '', '', 'youtube-live-likes-dislikes-counter.php', 1, 0),
(18, 'Youtube Channel Analytics', 'YouTube Channel Analytics - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgQW5hbHl0aWNzIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'youtube-channel-analytics.php', 1, 0),
(19, 'Find Channel ID', 'YouTube Channel ID Finder - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgSUQgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'find-youtube-channel-id.php', 1, 0),
(20, 'Generate embed', 'YouTube Channel ID Finder - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgSUQgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'youtube-embed-generator.php', 1, 0),
(21, 'Youtube Comments', 'YouTube Channel ID Finder - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgSUQgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'find-youtube-comments.php', 1, 0),
(22, 'Contact us', 'About Us - YT Tool Station', 'PGgxPkFib3V0IFVzLSBZVCBUb29sIFN0YXRpb248L2gxPg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+Jm5ic3A7aXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg==', '', '', '', 'contact_us.php', 0, 0),
(23, 'Terms & Conditions', 'Terms & Conditions - YT Tool Station', 'PGgxPkFib3V0IFVzLSBZVCBUb29sIFN0YXRpb248L2gxPg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+Jm5ic3A7aXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg==', '', '', '', 'terms-and-conditions.php', 0, 0),
(24, 'Blog', 'Blog - YT Tool Station', 'PGgxPkFib3V0IFVzLSBZVCBUb29sIFN0YXRpb248L2gxPg0KPHA+PHN0cm9uZz5Mb3JlbSBJcHN1bTwvc3Ryb25nPiZuYnNwO2lzIHNpbXBseSBkdW1teSB0ZXh0IG9mIHRoZSBwcmludGluZyBhbmQgdHlwZXNldHRpbmcgaW5kdXN0cnkuIExvcmVtIElwc3VtIGhhcyBiZWVuIHRoZSBpbmR1c3RyeSdzIHN0YW5kYXJkIGR1bW15IHRleHQgZXZlciBzaW5jZSB0aGUgMTUwMHMsIHdoZW4gYW4gdW5rbm93biBwcmludGVyIHRvb2sgYSBnYWxsZXkgb2YgdHlwZSBhbmQgc2NyYW1ibGVkIGl0IHRvIG1ha2UgYSB0eXBlIHNwZWNpbWVuIGJvb2suIEl0IGhhcyBzdXJ2aXZlZCBub3Qgb25seSBmaXZlIGNlbnR1cmllcywgYnV0IGFsc28gdGhlIGxlYXAgaW50byBlbGVjdHJvbmljIHR5cGVzZXR0aW5nLCByZW1haW5pbmcgZXNzZW50aWFsbHkgdW5jaGFuZ2VkLiBJdCB3YXMgcG9wdWxhcmlzZWQgaW4gdGhlIDE5NjBzIHdpdGggdGhlIHJlbGVhc2Ugb2YgTGV0cmFzZXQgc2hlZXRzIGNvbnRhaW5pbmcgTG9yZW0gSXBzdW0gcGFzc2FnZXMsIGFuZCBtb3JlIHJlY2VudGx5IHdpdGggZGVza3RvcCBwdWJsaXNoaW5nIHNvZnR3YXJlIGxpa2UgQWxkdXMgUGFnZU1ha2VyIGluY2x1ZGluZyB2ZXJzaW9ucyBvZiBMb3JlbSBJcHN1bS48L3A+DQo8cD48c3Ryb25nPkxvcmVtIElwc3VtPC9zdHJvbmc+Jm5ic3A7aXMgc2ltcGx5IGR1bW15IHRleHQgb2YgdGhlIHByaW50aW5nIGFuZCB0eXBlc2V0dGluZyBpbmR1c3RyeS4gTG9yZW0gSXBzdW0gaGFzIGJlZW4gdGhlIGluZHVzdHJ5J3Mgc3RhbmRhcmQgZHVtbXkgdGV4dCBldmVyIHNpbmNlIHRoZSAxNTAwcywgd2hlbiBhbiB1bmtub3duIHByaW50ZXIgdG9vayBhIGdhbGxleSBvZiB0eXBlIGFuZCBzY3JhbWJsZWQgaXQgdG8gbWFrZSBhIHR5cGUgc3BlY2ltZW4gYm9vay4gSXQgaGFzIHN1cnZpdmVkIG5vdCBvbmx5IGZpdmUgY2VudHVyaWVzLCBidXQgYWxzbyB0aGUgbGVhcCBpbnRvIGVsZWN0cm9uaWMgdHlwZXNldHRpbmcsIHJlbWFpbmluZyBlc3NlbnRpYWxseSB1bmNoYW5nZWQuIEl0IHdhcyBwb3B1bGFyaXNlZCBpbiB0aGUgMTk2MHMgd2l0aCB0aGUgcmVsZWFzZSBvZiBMZXRyYXNldCBzaGVldHMgY29udGFpbmluZyBMb3JlbSBJcHN1bSBwYXNzYWdlcywgYW5kIG1vcmUgcmVjZW50bHkgd2l0aCBkZXNrdG9wIHB1Ymxpc2hpbmcgc29mdHdhcmUgbGlrZSBBbGR1cyBQYWdlTWFrZXIgaW5jbHVkaW5nIHZlcnNpb25zIG9mIExvcmVtIElwc3VtLjwvcD4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg==', '', '', '', 'blog.php', 0, 0),
(25, 'Top Youtube Channels', 'Top Youtube Channels - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgSUQgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'top-youtube-channels.php', 1, 0),
(26, 'Mp3 Player', 'YouTube Mp3 Player - YT Tool Station', 'PGgxPkFib3V0IFlUIENoYW5uZWwgSUQgRmluZGVyIFRvb2w8L2gxPg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+', '', '', '', 'youtube-mp3-player.php', 1, 0),
(27, 'Watch YT Age Restricted Videos', 'Watch YT Age Restricted Videos - YT Tool Station', 'PGgxPldhdGNoIFlvdVR1YmUgQWdlIHJlc3RyaWN0ZWQgVmlkZW9zIHdpdGhvdXQgc2lnbjwvaDE+DQo8ZGl2Pg0KPGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+DQo8ZGl2PiZuYnNwOzwvZGl2Pg0KPC9kaXY+', '', '', '', 'watch-age-restricted-videos.php', 1, 0);

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--
DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS  `posts` (
  `id` int(6) NOT NULL,
  `cat_id` int(3) NOT NULL DEFAULT '1',
  `title` varchar(255) NOT NULL,
  `contents` text NOT NULL,
  `post_image` varchar(255) DEFAULT NULL,
  `date_posted` text CHARACTER SET utf8,
  `postSlug` text CHARACTER SET utf8,
  `status` int(11) NOT NULL DEFAULT '0',
  `pstatus` int(1) NOT NULL DEFAULT '0',
  `tags` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `cat_id`, `title`, `contents`, `post_image`, `date_posted`, `postSlug`, `status`, `pstatus`, `tags`) VALUES
(1, 3, 'We Have A New Address – A Tour To My World', 'PHA+QXMgd2UgYWxsIGtub3csIGVtcGxveWVlcyBzcGVuZCBtb3JlIHRoYW4gaGFsZiBvZiB0aGVpciBkYXkgdGltZSBpbiB0aGUgb2ZmaWNlLiBBbmQsIGV4YWN0bHkgdGhhdCB3YXMgb3VyIGFpbSB3aGVuIHdlIGJ1aWx0IG91ciBuZXcgb2ZmaWNlLiBXZSBhZGRlZCBlYWNoIGVsZW1lbnQgdGhhdCBtYWtlcyBvdXIgZW1wbG95ZWUgY29tZm9ydGFibGUgYW5kIGNhbiB3b3JrIGZyZWVseSBpbiBvdXIgbmV3IG9mZmljZS4gTGV0cyBkZWVwIGRpdmUgaW4gdGhlIHRvdXIgb2YgRXhjZWxsZW50IFdlYndvcmxkJnJzcXVvO3MgbmV3IG9mZmljZS48L3A+DQo8cD5BcyB3ZSBhbGwga25vdywgZW1wbG95ZWVzIHNwZW5kIG1vcmUgdGhhbiBoYWxmIG9mIHRoZWlyIGRheSB0aW1lIGluIHRoZSBvZmZpY2UuIEFuZCwgZXhhY3RseSB0aGF0IHdhcyBvdXIgYWltIHdoZW4gd2UgYnVpbHQgb3VyIG5ldyBvZmZpY2UuIFdlIGFkZGVkIGVhY2ggZWxlbWVudCB0aGF0IG1ha2VzIG91ciBlbXBsb3llZSBjb21mb3J0YWJsZSBhbmQgY2FuIHdvcmsgZnJlZWx5IGluIG91ciBuZXcgb2ZmaWNlLiBMZXRzIGRlZXAgZGl2ZSBpbiB0aGUgdG91ciBvZiBFeGNlbGxlbnQgV2Vid29ybGQmcnNxdW87cyBuZXcgb2ZmaWNlLjwvcD4NCjxwPkFzIHdlIGFsbCBrbm93LCBlbXBsb3llZXMgc3BlbmQgbW9yZSB0aGFuIGhhbGYgb2YgdGhlaXIgZGF5IHRpbWUgaW4gdGhlIG9mZmljZS4gQW5kLCBleGFjdGx5IHRoYXQgd2FzIG91ciBhaW0gd2hlbiB3ZSBidWlsdCBvdXIgbmV3IG9mZmljZS4gV2UgYWRkZWQgZWFjaCBlbGVtZW50IHRoYXQgbWFrZXMgb3VyIGVtcGxveWVlIGNvbWZvcnRhYmxlIGFuZCBjYW4gd29yayBmcmVlbHkgaW4gb3VyIG5ldyBvZmZpY2UuIExldHMgZGVlcCBkaXZlIGluIHRoZSB0b3VyIG9mIEV4Y2VsbGVudCBXZWJ3b3JsZCZyc3F1bztzIG5ldyBvZmZpY2UuPC9wPg0KPHA+QXMgd2UgYWxsIGtub3csIGVtcGxveWVlcyBzcGVuZCBtb3JlIHRoYW4gaGFsZiBvZiB0aGVpciBkYXkgdGltZSBpbiB0aGUgb2ZmaWNlLiBBbmQsIGV4YWN0bHkgdGhhdCB3YXMgb3VyIGFpbSB3aGVuIHdlIGJ1aWx0IG91ciBuZXcgb2ZmaWNlLiBXZSBhZGRlZCBlYWNoIGVsZW1lbnQgdGhhdCBtYWtlcyBvdXIgZW1wbG95ZWUgY29tZm9ydGFibGUgYW5kIGNhbiB3b3JrIGZyZWVseSBpbiBvdXIgbmV3IG9mZmljZS4gTGV0cyBkZWVwIGRpdmUgaW4gdGhlIHRvdXIgb2YgRXhjZWxsZW50IFdlYndvcmxkJnJzcXVvO3MgbmV3IG9mZmljZS48L3A+DQo8cD5BcyB3ZSBhbGwga25vdywgZW1wbG95ZWVzIHNwZW5kIG1vcmUgdGhhbiBoYWxmIG9mIHRoZWlyIGRheSB0aW1lIGluIHRoZSBvZmZpY2UuIEFuZCwgZXhhY3RseSB0aGF0IHdhcyBvdXIgYWltIHdoZW4gd2UgYnVpbHQgb3VyIG5ldyBvZmZpY2UuIFdlIGFkZGVkIGVhY2ggZWxlbWVudCB0aGF0IG1ha2VzIG91ciBlbXBsb3llZSBjb21mb3J0YWJsZSBhbmQgY2FuIHdvcmsgZnJlZWx5IGluIG91ciBuZXcgb2ZmaWNlLiBMZXRzIGRlZXAgZGl2ZSBpbiB0aGUgdG91ciBvZiBFeGNlbGxlbnQgV2Vid29ybGQmcnNxdW87cyBuZXcgb2ZmaWNlLjwvcD4=', '1b5c04a2828cac62e0ce192745a86c13.jpg', '2019-09-19', 'gifts-by-occasions', 0, 0, 'youtube,video,Great content,Happy'),
(2, 2, 'GIFTS BY OCCASIONS GRE', 'PHA+a25lZGtzbmxrZHMgayBzZGtsIGtsZHNmb21zZHBbIFtwJm5ic3A7IHdbcWRxayBwcXdbPC9wPg==', '14152-hello.jpg', '2020-03-05 06:00:54', 'mission-values-culture', 3, 0, NULL),
(3, 2, 'GIFTS BY OCCASIONS GRDNJNK NKJ JKNJKN JKN', 'PHA+a25lZGtzbmxrZHMgayBzZGtsIGtsZHNmb21zZHBbIFtwJm5ic3A7IHdbcWRxayBwcXdbPC9wPg0KPHA+Jm5ic3A7PC9wPg0KPHA+R0lGVFMgQlkgT0NDQVNJT05TIEdSRE5KTksgTktKIEpLTkpLTiBKS048L3A+DQo8cD4mbmJzcDs8L3A+DQo8cD5HSUZUUyBCWSBPQ0NBU0lPTlMgR1JETkpOSyBOS0ogSktOSktOIEpLTjwvcD4NCjxwPkdJRlRTIEJZIE9DQ0FTSU9OUyBHUkROSk5LIE5LSiBKS05KS04gSktOPC9wPg0KPHA+R0lGVFMgQlkgT0NDQVNJT05TIEdSRE5KTksgTktKIEpLTkpLTiBKS048L3A+DQo8cD5HSUZUUyBCWSBPQ0NBU0lPTlMgR1JETkpOSyBOS0ogSktOSktOIEpLTjwvcD4NCjxwPkdJRlRTIEJZIE9DQ0FTSU9OUyBHUkROSk5LIE5LSiBKS05KS04gSktOJm5ic3A7PC9wPg0KPHA+R0lGVFMgQlkgT0NDQVNJT05TIEdSRE5KTksgTktKIEpLTkpLTiBKS048L3A+DQo8cD5HSUZUUyBCWSBPQ0NBU0lPTlMgR1JETkpOSyBOS0ogSktOSktOIEpLTjwvcD4NCjxwPkdJRlRTIEJZIE9DQ0FTSU9OUyBHUkROSk5LIE5LSiBKS05KS04gSktOPC9wPg==', 'bride@2x.png', '2020-03-05 06:02:35', 'case-studies', 0, 0, NULL),
(4, 2, 'GIFTS BY OCCASIONS GRE', 'PHA+a25lZGtzbmxrZHMgayBzZGtsIGtsZHNmb21zZHBbIFtwJm5ic3A7IHdbcWRxayBwcXdbPC9wPg==', 'bride.png', '2020-03-06 06:55:05', 'gifts-by-occasions-new', 0, 0, 'youtube,jio'),
(5, 8, 'Rachana Phadke Ranade', 'PHA+UmFjaGFuYSBpcyBhIGNoYXJ0ZXJlZCBhY2NvdW50YW50LCBmYWN1bHR5IG1lbWJlciBhdCB0aGUgSW5zdGl0dXRlIG9mIENoYXJ0ZXJlZCBBY2NvdW50YW50cyBvZiBJbmRpYSwgdHJhaW5lZCBpbiBJbmRpYW4gY2xhc3NpY2FsIG11c2ljLCBhIG1vbSwgYW5kIGlzIGF0IHRoZSBoZWxtIG9mIGEgNDAwSysgc3Ryb25nIFlvdVR1YmUgY2hhbm5lbCwgd2hlcmUgc2hlIGVkdWNhdGVzIGhlciB2aWV3ZXJzIG9uIGZpbmFuY2UsIGJ1c2luZXNzLCBhbmQgbWFya2V0cy4gSGVyIGNoYW5uZWwgdGVhbSBoYXMgZ3Jvd24gZnJvbSB0d28gcGVvcGxlIHRvIGZpdmUsIGluY2x1ZGluZyByZXNlYXJjaGVycyBhbmQgYSB2aWRlbyBwcm9kdWNlci48YnIgLz48YnIgLz5BIE5leHRVcCBXb21lbiB0byBXYXRjaCB3aW5uZXIgaW4gSW5kaWEsIHNoZSdzIHBhc3Npb25hdGUgYWJvdXQgZXF1aXBwaW5nIHdvbWVuIHRvIGJlIGZpbmFuY2lhbGx5IGluZGVwZW5kZW50LiBTaGUmcnNxdW87cyBvbmUgb2YgdGhlIGZldyBjcmVhdG9ycyBpbiBhIHRyYWRpdGlvbmFsbHkgbWFsZS1kcml2ZW4gYXJlbmEgb2YgZmluYW5jaWFsIGVkdWNhdGlvbiBpbiBJbmRpYS48YnIgLz48YnIgLz48c3Ryb25nPllUOiZuYnNwO1doYXQgYXJlIHlvdSBtb3N0IHByb3VkIG9mIGZyb20geW91ciB3b3JrIG9uIFlvdVR1YmU/PC9zdHJvbmc+PGJyIC8+PHN0cm9uZz48YnIgLz48L3N0cm9uZz48c3Ryb25nPlJhY2hhbmE6PC9zdHJvbmc+Jm5ic3A7JmxkcXVvO0kgZmVlbCBwcm91ZCBvZiB0aGUgZmFjdCB0aGF0IG15IG1vc3Qgdmlld2VkIGxlY3R1cmUgb24gWW91dHViZSB3aGljaCBoYXMgY3Jvc3NlZCAyLjQgbWlsbGlvbiB2aWV3cyBpcyBhIDEuNSBob3VycyBsZWN0dXJlISBFbmNvdXJhZ2luZyBwZW9wbGUgdG8gY2xpY2sgb24gc3VjaCBhIGxvbmcgbGVjdHVyZSBhbmQga2VlcGluZyB0aGVtIGdsdWVkIHRvIGl0IGZvciBhIHN1YnN0YW50aWFsIHRpbWUgbWFrZXMgbWUgZmVlbCByZWFsbHkgZ29vZC48YnIgLz48YnIgLz5JIGFsc28gZmVlbCBwcm91ZCB0aGF0IHBlb3BsZSBmcm9tIHRoZSBJbmRpYW4gTmF2eSwgSW5kaWFuIEFpcmZvcmNlIGFuZCBJbmRpYW4gQXJteSBhbHNvIHdhdGNoIG15IGxlY3R1cmVzLiBJIGhhdmUgcmVjZWl2ZWQgbWFueSBjb21tZW50cyBmcm9tIHRoZW0gb24gbWFueSBvZiBteSB2aWRlb3MhIFNvLCBJIGZlZWwgcHJvdWQgb2YgdGhlIGZhY3QgdGhhdCBJIGFtIGFibGUgdG8gc2VydmUgdGhvc2Ugd2hvIHNlcnZlIG91ciBuYXRpb24hJnJkcXVvOzwvcD4=', '5d24ee309e578c6067a23a7b50f05c66.png', '2020-03-09 21:19:29', 'rachana-phadke-ranade', 3, 1, 'Rachana Phadke Ranade'),
(6, 10, 'Mission, Values & Culture sd54c56', 'PHA+ZXM2NTVjczRkNXY1NnNkNjV2IHM1IDY1NkRGIDU2c2Q1Jm5ic3A7IDVzZDwvcD4=', '14152-hello.jpg', '2019-12-19', 'mission-values-culture-sd54c56', 3, 1, 'u'),
(7, 2, 'Terms and conditions - Insta Tools', '', 'ice_screenshot_20200302-174254.png', '2222-02-22', 'terms-and-conditions-insta-tools', 3, 0, 'waedqwe'),
(8, 3, 'Terms and conditions - Insta Tools', 'PHA+d2R3YTwvcD4=', 'ice_screenshot_20200311-225154.png', '0022-02-22', 'terms-and-conditions-insta-tools', 0, 0, 'awda'),
(9, 6, 'We Have A New Address – A Tour To My World', 'PHA+V2UgSGF2ZSBBIE5ldyBBZGRyZXNzICZuZGFzaDsgQSBUb3VyIFRvIE15IFdvcmxkPC9wPg==', 'blog-img-1.jpg', '', 'we-have-a-new-address-a-tour-to-my-world', 0, 0, 're'),
(10, 6, 'We Have A New Address – A Tour To My World', 'PHA+V2UgSGF2ZSBBIE5ldyBBZGRyZXNzICZuZGFzaDsgQSBUb3VyIFRvIE15IFdvcmxkPC9wPg==', 'blog-img-1.jpg', '2020-03-11 20:35:23', 'we-have-a-new-address-a-tour-to-my-world', 4, 0, 're'),
(11, 3, 'We Have A New Address – A Tour To My World', 'PHA+cmVlcmdyZWdlPC9wPg==', 'blog-img-1.jpg', '2020-03-11 20:37:48', 'we-have-a-new-address-a-tour-to-my-world1583959068', 0, 0, 're'),
(12, 8, 'PDO with INSERT INTO through prepared statementsawfwfwfwe', 'PHA+UERPIHdpdGggSU5TRVJUIElOVE8gdGhyb3VnaCBwcmVwYXJlZCBzdGF0ZW1lbnRzYXdmd2Z3ZndlPC9wPg==', 'f0493d3d569bc7539122c5679d221396.jpg', '2020-03-11 20:41:55', 'pdo-with-insert-into-through-prepared-statementsawfwfwfwe1583959315', 0, 0, 'sad w,fewf,wdqwd'),
(13, 3, 'Terms and conditions - Insta Tools', '', 'blog-img-1.jpg', '2020-03-11 21:00:32', 'terms-and-conditions-insta-tools1583960432', 3, 0, ''),
(14, 3, 'Terms and conditions - Insta Tools', '', 'blog-img-1.jpg', '2020-03-11 21:04:54', 'terms-and-conditions-insta-tools1583960694', 3, 0, ''),
(15, 3, '9 Tips for Your YouTube SEO Strategy - Yt Tool Station', 'PGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPHA+SXQgaXMgYSBsb25nIGVzdGFibGlzaGVkIGZhY3QgdGhhdCBhIHJlYWRlciB3aWxsIGJlIGRpc3RyYWN0ZWQgYnkgdGhlIHJlYWRhYmxlIGNvbnRlbnQgb2YgYSBwYWdlIHdoZW4gbG9va2luZyBhdCBpdHMgbGF5b3V0LiBUaGUgcG9pbnQgb2YgdXNpbmcgTG9yZW0gSXBzdW0gaXMgdGhhdCBpdCBoYXMgYSBtb3JlLW9yLWxlc3Mgbm9ybWFsIGRpc3RyaWJ1dGlvbiBvZiBsZXR0ZXJzLCBhcyBvcHBvc2VkIHRvIHVzaW5nICdDb250ZW50IGhlcmUsIGNvbnRlbnQgaGVyZScsIG1ha2luZyBpdCBsb29rIGxpa2UgcmVhZGFibGUgRW5nbGlzaC4gTWFueSBkZXNrdG9wIHB1Ymxpc2hpbmcgcGFja2FnZXMgYW5kIHdlYiBwYWdlIGVkaXRvcnMgbm93IHVzZSBMb3JlbSBJcHN1bSBhcyB0aGVpciBkZWZhdWx0IG1vZGVsIHRleHQsIGFuZCBhIHNlYXJjaCBmb3IgJ2xvcmVtIGlwc3VtJyB3aWxsIHVuY292ZXIgbWFueSB3ZWIgc2l0ZXMgc3RpbGwgaW4gdGhlaXIgaW5mYW5jeS4gVmFyaW91cyB2ZXJzaW9ucyBoYXZlIGV2b2x2ZWQgb3ZlciB0aGUgeWVhcnMsIHNvbWV0aW1lcyBieSBhY2NpZGVudCwgc29tZXRpbWVzIG9uIHB1cnBvc2UgKGluamVjdGVkIGh1bW91ciBhbmQgdGhlIGxpa2UpLjwvcD4NCjxwPiZuYnNwOzwvcD4NCjxwPiZuYnNwOzwvcD4NCjxwPiZuYnNwOzwvcD4NCjwvZGl2Pg0KPGRpdj4mbmJzcDs8L2Rpdj4=', 'youtube_seo_blog_thumbnail-768x430-1.png', '2020-03-20 13:48:08', '9-tips-for-your-youtube-seo-strategy-yt-tool-station1584726488', 3, 0, 'youtube,seo,youtube seo'),
(16, 10, '9 Tips for Your YouTube SEO Strategy - Yt Tool Station', 'PGRpdj4NCjxwPjxzdHJvbmc+TG9yZW0gSXBzdW08L3N0cm9uZz4mbmJzcDtpcyBzaW1wbHkgZHVtbXkgdGV4dCBvZiB0aGUgcHJpbnRpbmcgYW5kIHR5cGVzZXR0aW5nIGluZHVzdHJ5LiBMb3JlbSBJcHN1bSBoYXMgYmVlbiB0aGUgaW5kdXN0cnkncyBzdGFuZGFyZCBkdW1teSB0ZXh0IGV2ZXIgc2luY2UgdGhlIDE1MDBzLCB3aGVuIGFuIHVua25vd24gcHJpbnRlciB0b29rIGEgZ2FsbGV5IG9mIHR5cGUgYW5kIHNjcmFtYmxlZCBpdCB0byBtYWtlIGEgdHlwZSBzcGVjaW1lbiBib29rLiBJdCBoYXMgc3Vydml2ZWQgbm90IG9ubHkgZml2ZSBjZW50dXJpZXMsIGJ1dCBhbHNvIHRoZSBsZWFwIGludG8gZWxlY3Ryb25pYyB0eXBlc2V0dGluZywgcmVtYWluaW5nIGVzc2VudGlhbGx5IHVuY2hhbmdlZC4gSXQgd2FzIHBvcHVsYXJpc2VkIGluIHRoZSAxOTYwcyB3aXRoIHRoZSByZWxlYXNlIG9mIExldHJhc2V0IHNoZWV0cyBjb250YWluaW5nIExvcmVtIElwc3VtIHBhc3NhZ2VzLCBhbmQgbW9yZSByZWNlbnRseSB3aXRoIGRlc2t0b3AgcHVibGlzaGluZyBzb2Z0d2FyZSBsaWtlIEFsZHVzIFBhZ2VNYWtlciBpbmNsdWRpbmcgdmVyc2lvbnMgb2YgTG9yZW0gSXBzdW0uPC9wPg0KPC9kaXY+DQo8ZGl2Pg0KPHA+SXQgaXMgYSBsb25nIGVzdGFibGlzaGVkIGZhY3QgdGhhdCBhIHJlYWRlciB3aWxsIGJlIGRpc3RyYWN0ZWQgYnkgdGhlIHJlYWRhYmxlIGNvbnRlbnQgb2YgYSBwYWdlIHdoZW4gbG9va2luZyBhdCBpdHMgbGF5b3V0LiBUaGUgcG9pbnQgb2YgdXNpbmcgTG9yZW0gSXBzdW0gaXMgdGhhdCBpdCBoYXMgYSBtb3JlLW9yLWxlc3Mgbm9ybWFsIGRpc3RyaWJ1dGlvbiBvZiBsZXR0ZXJzLCBhcyBvcHBvc2VkIHRvIHVzaW5nICdDb250ZW50IGhlcmUsIGNvbnRlbnQgaGVyZScsIG1ha2luZyBpdCBsb29rIGxpa2UgcmVhZGFibGUgRW5nbGlzaC4gTWFueSBkZXNrdG9wIHB1Ymxpc2hpbmcgcGFja2FnZXMgYW5kIHdlYiBwYWdlIGVkaXRvcnMgbm93IHVzZSBMb3JlbSBJcHN1bSBhcyB0aGVpciBkZWZhdWx0IG1vZGVsIHRleHQsIGFuZCBhIHNlYXJjaCBmb3IgJ2xvcmVtIGlwc3VtJyB3aWxsIHVuY292ZXIgbWFueSB3ZWIgc2l0ZXMgc3RpbGwgaW4gdGhlaXIgaW5mYW5jeS4gVmFyaW91cyB2ZXJzaW9ucyBoYXZlIGV2b2x2ZWQgb3ZlciB0aGUgeWVhcnMsIHNvbWV0aW1lcyBieSBhY2NpZGVudCwgc29tZXRpbWVzIG9uIHB1cnBvc2UgKGluamVjdGVkIGh1bW91ciBhbmQgdGhlIGxpa2UpLjwvcD4NCjwvZGl2Pg==', 'youtube_seo_blog_thumbnail-768x430-1.png', '2020-03-20', '9-tips-for-your-youtube-seo-strategy-yt-tool-station1584726632', 3, 0, 'youtube, seo,youtube seo');

-- --------------------------------------------------------

--
-- Table structure for table `settings`
--

DROP TABLE IF EXISTS `settings`;
CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(1) NOT NULL,
  `siteTitle` varchar(255) DEFAULT NULL,
  `metaKeywords` varchar(255) DEFAULT NULL,
  `metaDescription` varchar(255) DEFAULT NULL,
  `logoTxt` varchar(50) DEFAULT NULL,
  `logoImg` varchar(255) DEFAULT NULL,
  `footer` text
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `settings`
--

INSERT INTO `settings` (`id`, `siteTitle`, `metaKeywords`, `metaDescription`, `logoTxt`, `logoImg`, `footer`) VALUES
(1, 'YT Tool Station - 100% Free Best Online YouTube Tools', 'YT Tool Station - 100% Free Best Online YouTube Tools', 'YT Tool Station is a bundled collection of best tools for YouTube  videos.Such as Tags generator, y2mp3 Converter, live subscribers counter   & more.', 'YT Station', 'ytseotoolss-logo.png', 'RGVzaWduICYgRGV2ZWxvcCBieSA8YSBocmVmPSIjIj5NV1QuIExha3NoYW48L2E+'),
(2, '', '', '', '3', '', ''),
(3, '', '', '', '1.1', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `ads`
--
ALTER TABLE `ads`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `custom_codes`
--
ALTER TABLE `custom_codes`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `pages`
--
ALTER TABLE `pages`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `settings`
--
ALTER TABLE `settings`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `ads`
--
ALTER TABLE `ads`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(3) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `pages`
--
ALTER TABLE `pages`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=28;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(6) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- AUTO_INCREMENT for table `settings`
--
ALTER TABLE `settings`
  MODIFY `id` int(1) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
